receipt/success/pdf/template.hbs
=> chore: Add vers

.github/workflows/update_pdf_engine_template.yml, .github/workflows/update_receipt_notifier_markdown.yml, io-message/templates/debtor.json, io-message/templates/helm/values-dev.yaml, io-message/templates/payer.json, receipt/success/pdf/package.json
- Added GHA to open a pull request on `pagopa-receipt-pdf-notifier` repository when io messages markown are updated
=> [PRDP-143] feat: Add GHA for automatic pr to notifier

.github/workflows/update_receipt_notifier_markdown.yml, io-message/templates/debtor.json, io-message/templates/helm/values-dev.yaml
=> fix: GHA notifier msg upd

receipt/success/json/authenticated-apple-pay-pdf.json, receipt/success/json/authenticated-extra-fee-pdf.json, receipt/success/json/authenticated-multiple-cart-items-pdf.json, receipt/success/json/authenticated-pdf.json, receipt/success/json/guest-multiple-cart-items-requested-debtor-pdf.json, receipt/success/json/guest-requested-debtor-pdf.json, receipt/success/pdf/template.hbs
This PR adds dynamic values for the PSP section of the template.
- Add the new JSON with PSP-related data
- Update template accordingly
- Bumb template version
=> chore: Add dynamic values for PSP

.github/workflows/update_receipt_notifier_markdown.yml, io-message/templates/debtor.json
- Added base64 encoding to subject and markdown to preserve special characters
Show correctly subject and markdown in notification message
=> [PRDP-156] fix: Added base64 encoding to subject and markdown

.github/workflows/update_receipt_notifier_markdown.yml
=> [PRDP-156] fix: Base64 encoding

.github/workflows/update_receipt_notifier_markdown.yml
- Removed base64 encoding
Correctly show notification message
=> [PRDP-157] fix: Removed base64 encoding

io-message/templates/debtor.json
=> fix: Carriage return message

.github/workflows/update_receipt_notifier_markdown.yml
=> fix: Gha upd notifier

receipt/success/pdf/template.hbs
=> fix: UC3 template

receipt/success/pdf/template.hbs
This PR updates the template to reflect the latest data model.
- Update `RRN` copy
- Remove user mail block
- Remove redundant PSP block on the left column
=> chore: Remove useless data from the template

receipt/success/pdf/template.hbs
=> fix: Fee amount view

io-message/templates/payer.json
> Modified IO message payer markdown
=> [PRDP-174] feat: Update IO message payer markdown

receipt/success/pdf/template.hbs
- Extrapolated transaction.psp.name from requestedByDebtor condition
The debtor template (partial template) needs to see the psp name
=> [fix-psp-debtor] Extrapolated transaction.psp.name from debtor condition

receipt/success/pdf/style.css, receipt/success/pdf/template.hbs
This PR fixes line-height with long PSP names
- Fix line-height values with long PSP names
=> fix: Fix line-height with long PSP names

.github/workflows/update_psp_info_file.yml
- Introducing automated pipeline to update the psp_info file inside the receipt pdf generator
=> Feat add auto push of psp file

receipt/success/pdf/style.css, receipt/success/pdf/template.hbs
This PR makes payment subject optional.
- Update CSS to manage the CSS grid without payment subject
- Update template logic with the relative condition
=> chore: Make payment subject optional

receipt/success/pdf/template.hbs
This PR updates the receipt footer copy to avoid misunderstandings with our customers.
- Update template footer
=> chore: Update receipt footer with reference to transaction ID

receipt/success/json/authenticated-apple-pay-pdf.json, receipt/success/json/authenticated-extra-fee-pdf.json, receipt/success/json/authenticated-multiple-cart-items-pdf.json, receipt/success/json/authenticated-pdf.json, receipt/success/json/guest-multiple-cart-items-requested-debtor-pdf.json, receipt/success/json/guest-requested-debtor-pdf.json, receipt/success/json/schema/receipt.json, receipt/success/pdf/template.hbs
- added new field `serviceCustomerId`
- removed field `transaction.id`
- updated receipt schema
=> [PRDP-215] chore: Add serviceCustomerId

.github/workflows/update_pdf_engine_template.yml, .github/workflows/update_psp_info_file.yml
- Introducing GHA changes to create PR for template on receipts-helpdesk
=> [PRDP-250] feat: add pr to helpdesk in GHA

receipt/success/pdf/template.hbs
This PR updates the text associated with the PSP logo at the top right of the page.
- Update copy
=> chore: Update copy related to the PSP logo

receipt/success/json/authenticated-pdf.json, receipt/success/pdf/style.css, receipt/success/pdf/yarn.lock
This PR forces uppercase for tax code values
- Update `style.css` to force uppercase for code values (rendered in monospaced font)
=> chore: Force uppercase for tax code values

py-scripts/psp/output/psp_config_file.json
Add Worldpay B.V. configuration
This change allows to generate pdf receipt when for the transactions managed by Worldpay
=> feat: Add WOLLNLB1 psp configuration

py-scripts/psp/output/psp_config_file.json
=> feat: Add new BIC/IDPSP MOONEY `MOONITMMXXX` too

.identity/.terraform.lock.hcl, .identity/00_data.tf, .identity/03_github_environment.tf, .identity/99_main.tf
=> chore: [PAGOPA-3216] Identity
